In [1]:
%pip install torch torchvision torchaudio


   ---------------------------------------- 0.0/203.0 MB ? eta -:--:--
   ---------------------------------------- 1.0/203.0 MB 7.2 MB/s eta 0:00:28
    --------------------------------------- 3.9/203.0 MB 10.7 MB/s eta 0:00:19
   - -------------------------------------- 5.5/203.0 MB 9.9 MB/s eta 0:00:21
   - -------------------------------------- 8.1/203.0 MB 11.7 MB/s eta 0:00:17
   - -------------------------------------- 9.7/203.0 MB 10.1 MB/s eta 0:00:20
   -- ------------------------------------- 12.8/203.0 MB 10.6 MB/s eta 0:00:18
   -- ------------------------------------- 14.7/203.0 MB 10.4 MB/s eta 0:00:19
   --- ------------------------------------ 16.5/203.0 MB 10.2 MB/s eta 0:00:19
   --- ------------------------------------ 19.7/203.0 MB 10.7 MB/s eta 0:00:18
   ---- ----------------------------------- 22.5/203.0 MB 11.1 MB/s eta 0:00:17
   ---- ----------------------------------- 24.9/203.0 MB 11.0 MB/s eta 0:00:17
   ----- ---------------------------------- 27.0/203.0 M

In [2]:
import torch

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.numel()

12

In [5]:
x.shape

torch.Size([12])

In [6]:
X = x.reshape(-1, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
torch.ones((3, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.rand(3,4)

tensor([[0.8741, 0.2903, 0.4300, 0.0747],
        [0.7704, 0.2484, 0.7356, 0.6836],
        [0.4902, 0.6999, 0.8558, 0.5955]])

In [9]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

Indexing and Slicing


In [10]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [12]:
X[2,3] = 11
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [13]:
X[:2,:]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

Operations:


In [14]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [15]:
x= torch.tensor([1.0,2,4,8])
y= torch.tensor([2,2,2,2])
x+y, x-y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [16]:
X= torch.arange(12, dtype=torch.float32).reshape((3,4))
Y= torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
X.sum()

tensor(66.)

Broadcasting

In [19]:
a= torch.arange(3).reshape((3,1))
b= torch.arange(3).reshape((1,3))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1, 2]]))

In [20]:
a+b

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

Saving Memory

In [21]:
before =id(Y)
Y=Y+X
id(Y)== before

False

In [22]:
Z= torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:]=X+Y
print('id(Z):',id(Z))

id(Z): 2204030223520
id(Z): 2204030223520


In [23]:
before = id(X)
X += Y
id(X) == before

True

In [24]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [25]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

2.1.8 Exercises

Run the code in this section. Change the conditional statement X == Y to X < Y or X > Y, and then see what kind of tensor you can get.

In [26]:
X<Y 

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

While replacing X==Y to X<Y or X>Y, the result of this operation is the Boolean values, as seen before, where every element represents the outcome of comparing corresponding elements of tensors X and Y. The Boolean tensor X < Y results in indicating for which parts the condition has been satisfied based on the element value of both X and Y. If all of these are 'False', then you may say a condition does not satisfy for any element.

In [27]:

# Create 3-dimensional tensors
a = torch.arange(6).reshape((2, 1, 3))
b = torch.arange(4).reshape((1, 2, 2))

print("Tensor a:")
print(a)
print("Tensor b:")
print(b)

# Perform elementwise addition using broadcasting
result = a + b
print("Result of a + b:")
print(result)


Tensor a:
tensor([[[0, 1, 2]],

        [[3, 4, 5]]])
Tensor b:
tensor([[[0, 1],
         [2, 3]]])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2