Linear Algebra

Scalars: Scalars are tensors that contain only one element. We will be using lower case letter like x and y to represent a scalar. Scalar can be added multiplied, divided and raised to a power.

In [2]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

# Perform basic operations
print(x + y)  # Addition
print(x * y)  # Multiplication
print(x / y)  # Division
print(x ** y) # Exponentiation



tensor(5.)
tensor(6.)
tensor(1.5000)
tensor(9.)


Vectors: A vector is like a list of numbers. Each number in the list is called an element of the vector. Vectors can be represented as a real-world data, like a real persons height, weight and age. 

In [4]:
import torch

x = torch.arange(3)
print(x)
print(len(x))  # Output: 3
print(x.shape)  # Output: torch.Size([3])



tensor([0, 1, 2])
3
torch.Size([3])


Matrices: Martices are the 2 dimesntional array of numbers arranged in rows and columns. Its like a table of numbers.

In [6]:
A = torch.arange(6).reshape((3, 2))
print(A)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


Tensors: Tensors are generalization of matrics to more dimensions. They can have any number of axes.

In [7]:
tensor = torch.arange(24).reshape((2, 3, 4))
print(tensor)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


Basic Properties of Tensor Arithemetic: Scalars, vectors, matrices, and higher-order tensors all have some handy properties. For example, elementwise operations produce outputs that have the same shape as their operands.

In [11]:
A = torch.arange(6, dtype=torch.float32).reshape((2, 3))
B = A.clone()  # Make a copy of A
A, A+B, 

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]),
 tensor([[ 0.,  1.,  4.],
         [ 9., 16., 25.]]))

In [12]:
A*B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [14]:
a =2 
X= torch.arange(24).reshape(2,3,4)
a+X, (a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

Reduction: We often have to calculate the sum of the tensor's element. You can sum all elements of tensor or along specific axes.

In [15]:
A.sum()
A.sum(axis=0)
A.sum(axis=1)


tensor([ 3., 12.])

Mean: You can calculate the mean of elements in a tensor

In [16]:
A.mean()
A.mean(axis=0)
A.mean(axis=1)


tensor([1., 4.])

Dot Products: The dot product of two vectors is the sum of the products of their corresponding elements

In [17]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
print(torch.dot(x, y))


tensor(32)


Matrix-Vector Product: The matrix vector product is about how to multiply a matrix by a vector. When we multiply a matrix by a vector, we will get a new vector. The matrix transforms the vector into a different space. Lets take a matrix as a collection of row vectors. Each row vector represents a row of the matrix. To get the matrix-vector multiplication we take the dot product of each row vector with the input vector. The result is a new vector where each element is the dot product of the corresponding row vector and the input vector.

In [18]:
import torch

# Create a matrix A with shape (2, 3)
A = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Create a vector x with shape (3,)
x = torch.tensor([1, 2, 3])

# Perform matrix-vector multiplication
result = torch.mv(A, x)
print(result)


tensor([14, 32])


Norms: Norm is a way to measure the size or length of a vector. A norm is a function that maps a vector to a scalar, indicating the vector size. This satisfies three properties: Scaling, triangle inequality, ,and non negativity. 

In [19]:
import torch

u = torch.tensor([3.0, -4.0])
l2_norm = torch.norm(u)
print(l2_norm)  # Output: tensor(5.0)


tensor(5.)


In [20]:
import torch

u = torch.tensor([3.0, -4.0])
l1_norm = torch.abs(u).sum()
print(l1_norm)  # Output: tensor(7.0)


tensor(7.)


In [21]:
import torch

A = torch.ones((4, 9))
frobenius_norm = torch.norm(A)
print(frobenius_norm)  # Output: tensor(6.0)


tensor(6.)
